// types/question.ts
//
// Core data types for questions generated by the AI.
// These flow from /api/questions → NotebookCard → ChoiceList → HankoStamp.
// The same Question object is serialised into the logbook entry on correct answer.

// ─── Primitive types ──────────────────────────────────────────────────────────

/**
 * The four question types the AI generates.
 * Matches the sub-mode names except 'reading' which has no direct sub-mode equivalent
 * (reading comprehension is a sub-mode that generates 'reading' type questions).
 */
export type QuestionType = "vocabulary" | "grammar" | "reading" | "kanji";

/**
 * The four sub-modes available in study mode.
 * Used to scope AI generation and UI labels.
 */
export type SubMode = "vocabulary" | "grammar" | "kanji" | "reading";

/**
 * Maps kanji characters (or compounds) to their hiragana readings.
 * Every kanji appearing in the question stem must have an entry here.
 *
 * Example:
 *   { '電車': 'でんしゃ', '乗': 'の' }
 *
 * Used by FuriganaText.tsx to render <ruby> tags.
 * Stored in the database as a JSON string; parsed at read time.
 */
export interface FuriganaMap {
  [kanji: string]: string;
}

// ─── Question ─────────────────────────────────────────────────────────────────

/**
 * The exact shape returned by /api/questions and rendered by NotebookCard.
 *
 * The AI must return this shape exactly — the route handler validates it
 * with isValidQuestion() before sending to the client. Malformed responses
 * trigger one retry; two consecutive failures show the error card.
 */
export interface Question {
  /** Which question type this is */
  type: QuestionType;

  /**
   * The single word, particle, or kanji being tested.
   * Written to learnedWords.word on correct answer.
   * Empty string for reading comprehension questions.
   */
  targetWord: string;

  /**
   * Hiragana reading of targetWord.
   * e.g. 'でんしゃ' for 電車, 'やま·さん' for 山
   * Empty string for reading comprehension questions.
   */
  targetReading: string;

  /**
   * English meaning of targetWord.
   * e.g. 'train, electric train'
   * Empty string for reading comprehension questions.
   */
  targetMeaning: string;

  /**
   * The full Japanese question sentence displayed on the card.
   * For grammar questions: contains ＿＿＿ (fullwidth underscores) as the blank.
   * For reading questions: contains the comprehension question (passage is separate).
   */
  stem: string;

  /**
   * Furigana map for every kanji in `stem`.
   * Must be complete — missing entries leave kanji without readings.
   */
  furiganaMap: FuriganaMap;

  /**
   * English instruction line shown below the stem.
   * e.g. 'What does 電車 mean?' or 'Choose the correct particle.'
   */
  instruction: string;

  /**
   * Reading passage — present only for reading comprehension questions.
   * Displayed above the stem in PassageBlock.
   */
  passage?: string;

  /**
   * Furigana map for every kanji in `passage`.
   * Present only when `passage` is present.
   */
  passageFurigana?: FuriganaMap;

  /**
   * Exactly 4 answer choices. Never 3, never 5.
   * For vocabulary: English meanings.
   * For grammar: Japanese particles/forms in hiragana.
   * For kanji: hiragana readings.
   * For reading: English answers to the comprehension question.
   */
  choices: [string, string, string, string];

  /**
   * Index into `choices` of the correct answer (0–3).
   * Must correspond to the genuinely correct choice.
   */
  correctIndex: 0 | 1 | 2 | 3;

  /**
   * Explanation shown after the user answers.
   * 2–3 sentences. Reused verbatim in post-test review.
   */
  explanation: string;

  /**
   * Optional memory hook — a mnemonic or visual association.
   * Shown below the explanation when present.
   */
  memoryHook?: string;
}

// ─── Validation ───────────────────────────────────────────────────────────────

/**
 * Runtime type guard for Question.
 * Used by /api/questions to validate AI output before sending to the client.
 * Returns true only if the object is a well-formed Question.
 *
 * We check the minimum required fields. Optional fields (passage,
 * passageFurigana, memoryHook) are not required for validation to pass.
 */
export function isValidQuestion(q: unknown): q is Question {
  if (!q || typeof q !== "object") return false;

  const candidate = q as Record<string, unknown>;

  // Required string fields — must be non-empty strings
  const requiredStrings: (keyof Question)[] = [
    "targetWord",
    "targetMeaning",
    "stem",
    "instruction",
    "explanation",
  ];

  for (const field of requiredStrings) {
    if (typeof candidate[field] !== "string") return false;
  }

  // targetReading is required but may be empty string (reading type)
  if (typeof candidate["targetReading"] !== "string") return false;

  // type must be one of the four valid values
  const validTypes: QuestionType[] = [
    "vocabulary",
    "grammar",
    "reading",
    "kanji",
  ];
  if (!validTypes.includes(candidate["type"] as QuestionType)) return false;

  // furiganaMap must be an object (may be empty for reading questions)
  if (
    !candidate["furiganaMap"] ||
    typeof candidate["furiganaMap"] !== "object" ||
    Array.isArray(candidate["furiganaMap"])
  )
    return false;

  // choices must be an array of exactly 4 strings
  if (!Array.isArray(candidate["choices"])) return false;
  if (candidate["choices"].length !== 4) return false;
  if (!candidate["choices"].every((c) => typeof c === "string")) return false;

  // correctIndex must be 0, 1, 2, or 3
  const ci = candidate["correctIndex"];
  if (typeof ci !== "number") return false;
  if (ci < 0 || ci > 3) return false;

  return true;
}
